export const PREFIX_DETAIL = 'products'
export const EXCHANGE = 'exchange'
export const DAPP = 'dapp'
export const SOON = 'soon'
export const VENTURE = 'venture'
export const LAUNCHPAD = 'launchpad'
export const INSIGHT = 'insight'
export const SCAM = 'scam'
export const CRYPTO = 'crypto'
export const CRYPTO_COIN = 'coin'
export const CRYPTO_TOKEN = 'token'

export const CATEGORY_CRYPTO = 'Cryptos'
export const CATEGORY_DAPP = 'DApps'
export const CATEGORY_VENTURE = 'Ventures'
export const CATEGORY_EXCHANGE = 'Exchanges'
export const CATEGORY_SOON = 'ICO/IDO/IEO'
export const CATEGORY_LAUNCHPAD = 'Launchpads'
export const CATEGORY_INSIGHT = 'Insights'

export const LIST_CRYPTO = 'listCrypto'
export const LIST_VENTURE = 'listVenture'
export const LIST_SOON = 'listSoon'
export const LIST_EXCHANGE = 'listExchange'
export const LIST_DAPP = 'listDapp'
export const LIST_LAUNCHPAD = 'listLaunchpad'

